/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FileOP;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DuAn;
import model.NhanVien;
import model.QuanLy2;

/**
 *
 * @author Quang Vinh
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form QuanLy
     */
    ArrayList<DuAn> listDA;
    ArrayList<NhanVien> listNV;
    ArrayList<QuanLy2> listQL;
    ArrayList<Integer> listId;
    DefaultTableModel tableDA;
    DefaultTableModel tableNV;
    DefaultTableModel tableQL;
    public static String File_DA = "DA.txt";
    public static String File_NV = "NV.txt";
    public static String File_QL = "QL.txt";

    public QuanLy() {
        initComponents();
        listDA = new ArrayList<>();
        listNV = new ArrayList<>();
        listQL = new ArrayList<>();
        listId = new ArrayList<>();
        tableDA = (DefaultTableModel) jTable1.getModel();
        tableNV = (DefaultTableModel) jTable2.getModel();
        tableQL = (DefaultTableModel) jTable3.getModel();
        loadData();
        loadID();
        sort.addActionListener((e) -> {
            String type = sort.getSelectedItem().toString();
            if (type.equals("theo ten")) {
                Collections.sort(listQL, new Comparator<QuanLy2>() {
                    @Override
                    public int compare(QuanLy2 o1, QuanLy2 o2) {
                        return o1.getNhanvien().getName().compareTo(o2.getNhanvien().getName());
                    }
                });
            } else {
                Collections.sort(listQL, new Comparator<QuanLy2>() {
                    @Override
                    public int compare(QuanLy2 o1, QuanLy2 o2) {
                        return o2.getNgay() - o1.getNgay();
                    }
                });
            }
            tableQL.setRowCount(0);
            listQL.forEach((t) -> {
                tableQL.addRow(t.toObjects());
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nameDA = new javax.swing.JTextField();
        costDA = new javax.swing.JTextField();
        addDA = new javax.swing.JButton();
        saveDA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameNV = new javax.swing.JTextField();
        getPhone = new javax.swing.JTextField();
        addNV = new javax.swing.JButton();
        saveNV = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        getAddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ID1 = new javax.swing.JComboBox<>();
        loadID2 = new javax.swing.JComboBox<>();
        getNgay = new javax.swing.JTextField();
        addQuanLy = new javax.swing.JButton();
        saveQuanLy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        sort = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ten ");

        jLabel2.setText("Loai");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nho", "trung binh", "lon" }));

        jLabel3.setText("Kinh Phi");

        addDA.setText("Them");
        addDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDAActionPerformed(evt);
            }
        });

        saveDA.setText("luu file");
        saveDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDAActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma DA", "Ten DA", "Loai DA", "Kinh Phi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(costDA, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(nameDA)
                        .addComponent(saveDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addDA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(costDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addDA)
                .addGap(28, 28, 28)
                .addComponent(saveDA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Du An", jPanel1);

        jLabel4.setText("Ten ");

        jLabel6.setText("Dien Thoai");

        addNV.setText("Them");
        addNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNVActionPerformed(evt);
            }
        });

        saveNV.setText("luu file");
        saveNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNVActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma NV", "Ten NV", "SDT", "Dia Chi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("Dia Chi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(getPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(nameNV)
                        .addComponent(addNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(getAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(addNV)
                .addGap(18, 18, 18)
                .addComponent(saveNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhan Vien", jPanel3);

        jLabel5.setText("Ma Du An");

        jLabel8.setText("Ma Nhan Vien");

        jLabel9.setText("So Ngay");

        addQuanLy.setText("Them");
        addQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuanLyActionPerformed(evt);
            }
        });

        saveQuanLy.setText("Luu File");
        saveQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveQuanLyActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Du An", "Ten Du An", "Ma Nhan Vien", "Ten Nhan Vien", "Ngay"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("sap xep");

        sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "theo ten", "theo so ngay" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadID2, 0, 116, Short.MAX_VALUE)
                    .addComponent(ID1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getNgay)
                    .addComponent(addQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(getNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addQuanLy)
                .addGap(18, 18, 18)
                .addComponent(saveQuanLy)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Quan Ly Du An", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNVActionPerformed
        // TODO add your handling code here:
        String name = nameNV.getText();
        String address = getAddress.getText();
        String phone = getPhone.getText();
        if (name == "" || address == "" || phone == "") {
            JOptionPane.showMessageDialog(null, "Nhap thieu thong tin");
            return;
        }
        int currentPos = listNV.size() - 1;
        if (currentPos != -1) {
            NhanVien.setCurrentId(listNV.get(currentPos).getId());
        }
        NhanVien nhanvien = new NhanVien(name, address, phone);
        for (int i = 0; i < listNV.size(); i++) {
            if (listNV.get(i).getName().equals(nhanvien.getName())) {
                JOptionPane.showMessageDialog(null, "trung nhan vien");
                return;
            }
        }
        listNV.add(nhanvien);
        tableNV.addRow(nhanvien.toObjects());
        loadID();
    }//GEN-LAST:event_addNVActionPerformed

    private void saveNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNVActionPerformed
        // TODO add your handling code here:
        FileOP.writeToFile(listNV, File_NV);
        JOptionPane.showMessageDialog(null, "da luu thong tin nhan vien");
    }//GEN-LAST:event_saveNVActionPerformed

    private void addDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDAActionPerformed
        // TODO add your handling code here:
        String name = nameDA.getText();
        String type = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String cost = costDA.getText();
        if (name == "" || type == "" || cost == "") {
            JOptionPane.showMessageDialog(null, "Nhap thieu thong tin");
            return;
        }
        try {
            int Cost = Integer.parseInt(cost);
            int currentPos = listDA.size() - 1;
            if (currentPos != -1) {
                DuAn.setCurrentId(listDA.get(currentPos).getId());
            }
            DuAn duan = new DuAn(Cost, name, type);
            for (int i = 0; i < listDA.size(); i++) {
                if (listDA.get(i).getName().equals(duan.getName())) {
                    JOptionPane.showMessageDialog(null, "trung ma du an");
                    return;
                }
            }
            listDA.add(duan);
            tableDA.addRow(duan.toObjects());
            loadID();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Gia nhap sai dinh dang");
        }
    }//GEN-LAST:event_addDAActionPerformed

    private void saveDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDAActionPerformed
        // TODO add your handling code here:
        FileOP.writeToFile(listDA, File_DA);
        JOptionPane.showMessageDialog(null, "da luu thong tin nhan vien");
    }//GEN-LAST:event_saveDAActionPerformed

    private void addQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuanLyActionPerformed
        // TODO add your handling code here:
        int idQuanLy = ID1.getSelectedIndex();
        int idNhanVien = loadID2.getSelectedIndex();
        String ngay = getNgay.getText();
        try {
            int Ngay = Integer.parseInt(ngay);
            //QuanLy2 quanLly=new QuanLy2(DuAn, idNhanVien, Ngay);
            QuanLy2 q = new QuanLy2(listDA.get(idQuanLy), listNV.get(idNhanVien), Ngay);
            for (int i = 0; i < listQL.size(); i++) {
                if (listQL.get(i).getDuan().getName().equals(q.getDuan().getName()) && listQL.get(i).getNhanvien().getName().equals(q.getNhanvien().getName())) {
                    JOptionPane.showMessageDialog(null, "mot nhan vien khong the lam hai du an cung vi tri");
                    return;
                }
            }
            listQL.add(q);
            tableQL.addRow(q.toObjects());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "du lieu sai dinh dang");
        }
    }//GEN-LAST:event_addQuanLyActionPerformed

    private void saveQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveQuanLyActionPerformed
        // TODO add your handling code here:
        FileOP.writeToFile(listQL, File_QL);
        JOptionPane.showMessageDialog(null, "da luu thong tin cong viec");
    }//GEN-LAST:event_saveQuanLyActionPerformed
    private void loadData() {
        FileOP.readFromFile(listDA, File_DA);
        FileOP.readFromFile(listNV, File_NV);
        listDA.forEach((t) -> {
            tableDA.addRow(t.toObjects());
        });
        listNV.forEach((t) -> {
            tableNV.addRow(t.toObjects());
        });
    }

    private void loadID() {
        ID1.removeAllItems();
        loadID2.removeAllItems();
        listDA.forEach((t) -> {
            ID1.addItem(t.getId() + "");
        });
        listNV.forEach((t) -> {
            loadID2.addItem(t.getId() + "");
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ID1;
    private javax.swing.JButton addDA;
    private javax.swing.JButton addNV;
    private javax.swing.JButton addQuanLy;
    private javax.swing.JTextField costDA;
    private javax.swing.JTextField getAddress;
    private javax.swing.JTextField getNgay;
    private javax.swing.JTextField getPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> loadID2;
    private javax.swing.JTextField nameDA;
    private javax.swing.JTextField nameNV;
    private javax.swing.JButton saveDA;
    private javax.swing.JButton saveNV;
    private javax.swing.JButton saveQuanLy;
    private javax.swing.JComboBox<String> sort;
    // End of variables declaration//GEN-END:variables
}
